### ISSUE TITLE
Minifies url encoded svg images incorrectly in css files

### ISSUE THREAD

**Issue by deepvision7** [Chris2011/minifierbeans#62]
For example the following css statement
`background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3e%3cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3e%3c/svg%3e");`

becomes
`background-image:url("data:image/svg+xml,%3csvgxmlns='http://www.w3.org/2000/svg'fill='%23fff'viewBox='0088'%3e%3cpathd='M5.250l-44441.5-1.5-2.5-2.52.5-2.5-1.5-1.5z'/%3e%3c/svg%3e")`

making it `<svgxmlns...` instead of `<svg xmlns...`

**Comment by Chris2011** [comment]
Hey,

thx for the ticket, will have a look soon :)

**Comment by Chris2011** [comment]
It seems, that your CSS is broken. I can't get it working: https://codepen.io/chris2011-the-bashful/pen/BazWwXY here you can't see no result and if you try your snippet in the cssnano playground: https://cssnano.co/playground/ it breaks the whole application :D and gies some console errors.

**Comment by Chris2011** [comment]
I also unescaped your svg string. The SVG is working, when I use a separated file, but also not working on codepen (See commented code). When I use this code snippet:

```css
div {
  background-image: url('data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 166 166"><polygon fill="red" points="83 26.8 65.7 61.8 27.1 67.4 55 94.7 48.5 133.2 83 115 117.5 133.2 111 94.7 138.9 67.4 100.3 61.8 83 26.8 83 26.8"/></svg>'); 
}
```

codepen shows it. Anyway, I think there is smth missing in the config of cssnano. Will check this too.

**Comment by Chris2011** [comment]
Ok, my fault. I overseen the #fff :D. So ok your css is working, then there is smth missing in the cssnano.

**Comment by deepvision7** [comment]
Sorry, should have used a different colour to make it work by default.

**Comment by Chris2011** [comment]
No problem, I saw it :). As I said, will check it soon. Maybe I need to update the npm packages.

**Comment by Chris2011** [comment]
Also thx for pointing this out.

**Comment by deepvision7** [comment]
Thanks for the great plugin :)

Monday, October 26, 2020, 3:14:00 PM, you wrote:

C> Also thx for pointing this out.




Best regards

Taras

**Comment by Chris2011** [comment]
Thanks goes to the initial developer @jGauravGupta

**Comment by Chris2011** [comment]
Unfortunately, I can't reproduce it. I created a tester.css file and this is my code:

```css
body {
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3e%3cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3e%3c/svg%3e");
}
```

and it becomes this: 

```css
body{background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5L4.25 4l2.5-2.5L5.25 0z'/%3E%3C/svg%3E")}
```

I did a right click on the css file -> Minify CSS. Output opens and the successful notification.
